query getDiscussions($cursor: String) {
    repository(owner: "python-telegram-bot", name: "python-telegram-bot") {
        discussions(last: 100, before: $cursor) {
            nodes {
                number
                title
                url
                author {
                    login
                    url
                }
            }
            pageInfo {
                hasPreviousPage
                startCursor
            }
        }
    }
}