query getPTBContribs {
    repository(owner: "python-telegram-bot", name: "ptbcontrib") {
        object(expression: "main:ptbcontrib") {
            ... on Tree {
                entries {
                    name
                    type
                }
            }
        }
    }
}