name: Warning maintainers
on:
  pull_request_target:
    paths:
      - requirements.txt
      - .pre-commit-config.yaml
permissions:
 pull-requests: write
jobs:
  job:
    runs-on: ubuntu-latest
    name: about pre-commit and dependency change
    steps:
      - name: running the check
        uses: Poolitzer/notifier-action@master
        with:
          notify-message: Hey! Looks like you edited the requirements or the pre-commit hooks. I'm just a friendly reminder to keep the additional dependencies for the hooks in sync with the requirements :)
          repo-token: ${{ secrets.GITHUB_TOKEN }}